strHtml += "<div class='accordion accordion-solid accordion-toggle-plus' id='accordion_" + k + "'>"
strHtml += "    <div class='card'>"
strHtml += "        <div class='card-header' id='heading_" + k + "'>"
strHtml += "            <div class='card-title' data-toggle='collapse' data-target='#collapse_" + k + "'>"
strHtml += "                <nome>" + obj[k].oab + " " + obj[k].oab_uf + " - " + obj[k].nome_beneficiario + "</nome>"
strHtml += "                <input type='hidden' id='codBeneficiario-" + obj[k].cod_beneficiario + "' value='" + obj[k].cod_beneficiario + "'/>"
strHtml += "            </div>"
strHtml += "        </div>"
strHtml += "        <div id='collapse_" + k + "' class='collapse show' data-parent='accordion_" + k + "'>"
strHtml += "            <div class='card-body' id='benef-" + obj[k].cod_beneficiario + "'>"
strHtml += "            </div>"
strHtml += "        </div>"
strHtml += "    </div>"
strHtml += "</div>"


// Atual
strHtml += "<div class='panel panel-default'>"
strHtml += "    <div class='panel-benef'>"
strHtml += "        <h1 class='panel-title'>"
strHtml += "            <a href='#' data-toggle='collapse' data-target='#benef-" + obj[k].cod_beneficiario + "'>"
strHtml += "                <span class='glyphicon glyphicon-tag' aria-hidden='true'></span>"
strHtml += "                <nome>" + obj[k].oab + " " + obj[k].oab_uf + " - " + obj[k].nome_beneficiario + "</nome>"
strHtml += "                <input type='hidden' id='codBeneficiario-" + obj[k].cod_beneficiario + "' value='" + obj[k].cod_beneficiario + "'/>"
strHtml += "                <div class='setas'><span id='seta-" + obj[k].cod_beneficiario + "' class='glyphicon glyphicon-chevron-down' aria-hidden='true'></div>"
strHtml += "            </a>"
strHtml += "        </h1>"
strHtml += "    </div>"
strHtml += "    <div id='benef-" + obj[k].cod_beneficiario + "' class='panel-collapse collapse'>"
strHtml += "        <div class='panel-body'></div>"
strHtml += "    </div>"
strHtml += "</div>"